import { DocsContentShell } from "./DocsContentShell";
import { Callout, CodeCaption, DocHeader, NextStep } from "./_components";

export const DocsGoRuntime = () => {
	return (
		<DocsContentShell>
			<DocHeader title="Go Runtime">
				SHSF compiles your Go source once and caches the binary. Subsequent
				invocations run the cached binary directly — no recompile overhead.
				Go's static typing and built-in concurrency make it ideal for
				performance-sensitive functions.
			</DocHeader>

			<h2>Supported Go versions</h2>
			<ul>
				<li>golang:1.20</li>
				<li>golang:1.21</li>
				<li>golang:1.22</li>
				<li>golang:1.23</li>
			</ul>

			<h2>Entry point</h2>
			<p>
				Your code must define a <code>main_user</code> function. The SHSF
				runtime wraps it with <code>main()</code> — do not define your own{" "}
				<code>main</code>.
			</p>
			<CodeCaption>main.go — minimal function</CodeCaption>
			<pre>
				<code>{`package main

func main_user(args interface{}) (interface{}, error) {
    return map[string]string{"hello": "from Go"}, nil
}`}</code>
			</pre>

			<h2>Reading request data</h2>
			<p>
				<code>args</code> arrives as <code>map[string]interface{}</code>. Use
				a type assertion to access the fields:
			</p>
			<CodeCaption>Go — read body, queries, route</CodeCaption>
			<pre>
				<code>{`package main

import (
    "encoding/json"
    "fmt"
)

func main_user(args interface{}) (interface{}, error) {
    payload, ok := args.(map[string]interface{})
    if !ok {
        return nil, fmt.Errorf("unexpected args type")
    }

    // Parsed fields are strings from SHSF
    bodyStr, _ := payload["body"].(string)
    route,   _ := payload["route"].(string)
    method,  _ := payload["method"].(string)

    // Parse JSON body
    var data map[string]interface{}
    if bodyStr != "" {
        json.Unmarshal([]byte(bodyStr), &data)
    }

    return map[string]interface{}{
        "route":  route,
        "method": method,
        "data":   data,
    }, nil
}`}</code>
			</pre>

			<h2>Custom responses</h2>
			<CodeCaption>Go — v2 envelope</CodeCaption>
			<pre>
				<code>{`package main

func main_user(args interface{}) (interface{}, error) {
    return map[string]interface{}{
        "_shsf": "v2",
        "_code": 201,
        "_headers": map[string]string{
            "Content-Type": "application/json",
            "X-Powered-By": "SHSF",
        },
        "_res": map[string]string{"status": "created"},
    }, nil
}`}</code>
			</pre>

			<h2>Using Go modules (dependencies)</h2>
			<p>
				Create a <code>go.mod</code> file in the file manager. SHSF downloads
				and caches dependencies based on a hash of <code>go.mod</code> and{" "}
				<code>go.sum</code>.
			</p>
			<CodeCaption>go.mod</CodeCaption>
			<pre>
				<code>{`module myfunction

go 1.23

require (
    github.com/google/uuid v1.6.0
)`}</code>
			</pre>
			<CodeCaption>Using the dependency</CodeCaption>
			<pre>
				<code>{`package main

import "github.com/google/uuid"

func main_user(args interface{}) (interface{}, error) {
    return map[string]string{"id": uuid.NewString()}, nil
}`}</code>
			</pre>
			<Callout variant="info" title="go.sum is generated automatically">
				<p>
					SHSF runs <code>go mod tidy</code> during the init phase, so{" "}
					<code>go.sum</code> is created and updated for you. You only need to
					provide <code>go.mod</code>.
				</p>
			</Callout>

			<h2>Database communication</h2>
			<CodeCaption>Go — db_com quick start</CodeCaption>
			<pre>
				<code>{`package main

import "myfunction/dbcom"

func main_user(args interface{}) (interface{}, error) {
    db := dbcom.New()

    _, err := db.CreateStorage("cache", "")
    if err != nil { return nil, err }

    _, err = db.Set("cache", "key", "hello", nil)
    if err != nil { return nil, err }

    value, err := db.Get("cache", "key")
    if err != nil { return nil, err }

    return map[string]interface{}{"stored": value}, nil
}`}</code>
			</pre>

			<h2>Logging</h2>
			<p>
				Write to stdout or stderr — both are captured in the function execution
				log:
			</p>
			<CodeCaption>Go — logging</CodeCaption>
			<pre>
				<code>{`package main

import (
    "fmt"
    "log"
)

func main_user(args interface{}) (interface{}, error) {
    log.Println("function invoked")
    fmt.Println("processing request...")
    return map[string]bool{"ok": true}, nil
}`}</code>
			</pre>

			<h2>File structure</h2>
			<CodeCaption>Typical layout</CodeCaption>
			<pre>
				<code>{`myfunction/
├── main.go      ← startup file (set in function settings)
├── go.mod       ← module definition (optional)
└── go.sum       ← dependency checksums (auto-generated by go mod tidy)`}</code>
			</pre>

			<h2>Caching behaviour</h2>
			<ul>
				<li>
					The compiled binary is cached at{" "}
					<code>/go-cache/bin/function-&#123;id&#125;/_shsf_runner</code>.
				</li>
				<li>
					Recompilation is triggered when the hash of <code>.go</code> files,{" "}
					<code>go.mod</code>, or <code>go.sum</code> changes.
				</li>
				<li>
					Dependency downloads are cached separately from the binary.
				</li>
			</ul>

			<NextStep href="/docs/dotnet-runtime" label="#21 .NET Runtime">
				Next: build C# functions with SHSF's generated runtime helpers for
				payload loading, responses, and persistent storage.
			</NextStep>
		</DocsContentShell>
	);
};
