services:
  ui:
    image: node:22
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./UI:/app
    command: sh -c "npm install -g pnpm && pnpm i && pnpm tailwind:build && pnpm build && pnpm serve" 
    ports:
      - "5000:3000"

  backend:
    image: node:22
    working_dir: /app
    volumes:
      - ./Backend:/app
    command: sh -c "npm install -g pnpm && pnpm i && npx prisma generate && pnpm dev"
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - ui

  # database service disabled:
  # database:
  #   image: mariadb:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: exampledb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - ./Database:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #     test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3