name: Build Test
run-name: Build Test Workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ui_build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Working Directory
        run: cd UI
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Get NodeJs Ready
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Attempt to build
        run: pnpm build
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Working Directory
        run: cd Backend
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Get NodeJs Ready
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Attempt to build
        run: pnpm
  compose_validation:
    name: Validate Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose
      - name: Validate Docker Compose files
        run: docker-compose config
