name: Build Test
run-name: Build Test Workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  compose_validation:
    name: Validate Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose
      - name: Set up Docker Build
        run: touch .env
      - name: Validate Docker Compose files
        run: docker-compose config

  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install dependencies
        run: cd Backend && pnpm install
      - name: Build Backend
        run: cd Backend && pnpm build

  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install dependencies
        run: cd UI && pnpm install
      - name: Build Frontend
        run: cd UI && pnpm build
